# Generated by Django 4.0.6 on 2022-08-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seo_title', models.CharField(max_length=70)),
                ('seo_des', models.TextField(max_length=160)),
            ],
        ),
    ]
