# Generated by Django 4.0.6 on 2022-08-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0002_processorbrand_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('chipset', models.CharField(blank=True, max_length=120, null=True)),
                ('cpu', models.CharField(blank=True, max_length=150, null=True)),
                ('gpu', models.CharField(blank=True, max_length=50, null=True)),
                ('nm', models.CharField(blank=True, max_length=20, null=True)),
                ('released', models.DateField()),
                ('seo_title', models.CharField(max_length=70)),
                ('seo_des', models.TextField(max_length=160)),
            ],
        ),
        migrations.AlterModelOptions(
            name='processorbrand',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='processorbrand',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
