# Generated by Django 4.0.6 on 2022-08-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0005_alter_processor_options_processor_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='brands')),
                ('about', models.TextField(blank=True, null=True)),
                ('seo_title', models.CharField(max_length=70)),
                ('seo_des', models.TextField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=70, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='processorbrand',
            options={'ordering': ['name']},
        ),
    ]
