# Generated by Django 4.0.6 on 2022-08-05 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0007_alter_processor_brand_alter_processor_seo_des_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='phone'),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='phone')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phone.phone')),
            ],
        ),
    ]
