# Generated by Django 4.0.6 on 2022-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0008_phone_thumbnail_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='seo_des',
            field=models.TextField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='seo_title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
