# Generated by Django 4.0.6 on 2022-08-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0009_alter_phone_options_phone_name_phone_seo_des_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
