# Generated by Django 4.0.6 on 2022-08-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0010_phone_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='second_display',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='display_features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='seven_g',
            field=models.BooleanField(default=False),
        ),
    ]
