# Generated by Django 4.0.6 on 2022-08-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0011_phone_second_display_alter_phone_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='china',
            field=models.TextField(blank=True, null=True),
        ),
    ]
