# Generated by Django 4.0.6 on 2022-08-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0013_alter_phone_options_alter_galleryimage_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='old_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
