# Generated by Django 4.0.6 on 2022-09-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0015_phonebrand_published_alter_phone_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='camera_short',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
