# Generated by Django 4.0.6 on 2022-09-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0016_phone_camera_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='category',
            field=models.CharField(choices=[('Smartphone', 'Smartphone'), ('Tablet', 'Tablet'), ('Feature Phone', 'Feature Phone')], default='Smartphone', max_length=50),
        ),
    ]
