# Generated by Django 4.0.6 on 2022-09-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0018_alter_phone_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
