# Generated by Django 4.0.6 on 2022-09-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0019_alter_phone_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='rating',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
