# Generated by Django 4.0.6 on 2022-09-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0020_phone_rating_alter_phone_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
