# Generated by Django 4.0.6 on 2022-09-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0021_alter_phone_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
