# Generated by Django 4.0.6 on 2022-09-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0023_alter_phone_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='views',
        ),
    ]
