# Generated by Django 4.0.6 on 2022-09-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0025_phone_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='bluetooth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
