# Generated by Django 4.0.6 on 2023-04-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0026_phone_bluetooth'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
