# Generated by Django 4.0.6 on 2023-04-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0027_galleryimage_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
