# Generated by Django 4.0.6 on 2022-08-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='page_title',
            new_name='title',
        ),
    ]
